apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: database_password
    remoteRef:
      key: notification-service
      property: database_password
      version: latest
  - secretKey: database_host
    remoteRef:
      key: notification-service
      property: database_host
      version: latest
  - secretKey: session_token_key
    remoteRef:
      key: notification-service
      property: session_token_key
      version: latest
  - secretKey: apns_auth_key
    remoteRef:
      key: notification-service
      property: apns_auth_key
      version: latest
  - secretKey: webpush_vapid_public_key
    remoteRef:
      key: notification-service
      property: webpush_vapid_public_key
      version: latest
  - secretKey: webpush_vapid_private_key
    remoteRef:
      key: notification-service
      property: webpush_vapid_private_key
      version: latest
  - secretKey: river-rpc-url
    remoteRef:
      key: rpc_urls
      version: latest
      property: river